CREATE TABLE IF NOT EXISTS USERS (ID INT PRIMARY KEY NOT NULL, FIRST_NAME VARCHAR NOT NULL, LAST_NAME VARCHAR NOT NULL, AGE INT NOT NULL);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, AGE) VALUES (0, 'Liam', 'Huffman', 25);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, AGE) VALUES (1, 'Nicholas', 'Slabach', 27);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, AGE) VALUES (2, 'Rai', 'Dorzback', 25);
INSERT INTO USERS (ID, FIRST_NAME, LAST_NAME, AGE) VALUES (3, 'Austin', 'Robertson', 28);