// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: admin.proto
// Protobuf C++ Version: 6.31.0

#include "admin.pb.h"

#include <algorithm>
#include <type_traits>

#include "google/protobuf/descriptor.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/wire_format_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace admin {

inline constexpr AdminResponse::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
    : _cached_size_{0},
      message_(&::google::protobuf::internal::fixed_address_empty_string,
               ::_pbi::ConstantInitialized()),
      status_{static_cast<::admin::AdminStatus>(0)} {}

template <typename>
PROTOBUF_CONSTEXPR AdminResponse::AdminResponse(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AdminResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AdminResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AdminResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AdminResponseDefaultTypeInternal() {}
  union {
    AdminResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    AdminResponseDefaultTypeInternal _AdminResponse_default_instance_;

inline constexpr AccountRequest::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
    : _cached_size_{0}, account_id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR AccountRequest::AccountRequest(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(AccountRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AccountRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountRequestDefaultTypeInternal() {}
  union {
    AccountRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    AccountRequestDefaultTypeInternal _AccountRequest_default_instance_;

inline constexpr Account::Impl_::Impl_(::_pbi::ConstantInitialized) noexcept
    : _cached_size_{0},
      first_name_(&::google::protobuf::internal::fixed_address_empty_string,
                  ::_pbi::ConstantInitialized()),
      last_name_(&::google::protobuf::internal::fixed_address_empty_string,
                 ::_pbi::ConstantInitialized()),
      phone_number_(&::google::protobuf::internal::fixed_address_empty_string,
                    ::_pbi::ConstantInitialized()),
      password_(&::google::protobuf::internal::fixed_address_empty_string,
                ::_pbi::ConstantInitialized()),
      account_id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR Account::Account(::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(Account_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct AccountDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AccountDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AccountDefaultTypeInternal() {}
  union {
    Account _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
    AccountDefaultTypeInternal _Account_default_instance_;
}  // namespace admin
static const ::_pb::EnumDescriptor* PROTOBUF_NONNULL file_level_enum_descriptors_admin_2eproto[1];
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_admin_2eproto = nullptr;
const ::uint32_t TableStruct_admin_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    0x081,  // bitmap
    PROTOBUF_FIELD_OFFSET(::admin::Account, _impl_._has_bits_),
    8,  // hasbit index offset
    PROTOBUF_FIELD_OFFSET(::admin::Account, _impl_.account_id_),
    PROTOBUF_FIELD_OFFSET(::admin::Account, _impl_.first_name_),
    PROTOBUF_FIELD_OFFSET(::admin::Account, _impl_.last_name_),
    PROTOBUF_FIELD_OFFSET(::admin::Account, _impl_.phone_number_),
    PROTOBUF_FIELD_OFFSET(::admin::Account, _impl_.password_),
    4,
    0,
    1,
    2,
    3,
    0x081,  // bitmap
    PROTOBUF_FIELD_OFFSET(::admin::AccountRequest, _impl_._has_bits_),
    4,  // hasbit index offset
    PROTOBUF_FIELD_OFFSET(::admin::AccountRequest, _impl_.account_id_),
    0,
    0x081,  // bitmap
    PROTOBUF_FIELD_OFFSET(::admin::AdminResponse, _impl_._has_bits_),
    5,  // hasbit index offset
    PROTOBUF_FIELD_OFFSET(::admin::AdminResponse, _impl_.status_),
    PROTOBUF_FIELD_OFFSET(::admin::AdminResponse, _impl_.message_),
    1,
    0,
};

static const ::_pbi::MigrationSchema schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
    {0, sizeof(::admin::Account)},
    {13, sizeof(::admin::AccountRequest)},
    {18, sizeof(::admin::AdminResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::admin::_Account_default_instance_._instance,
    &::admin::_AccountRequest_default_instance_._instance,
    &::admin::_AdminResponse_default_instance_._instance,
};
const char descriptor_table_protodef_admin_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\013admin.proto\022\005admin\"\317\001\n\007Account\022\027\n\nacco"
    "unt_id\030\001 "
    "\001(\003H\000\210\001\001\022\027\n\nfirst_name\030\002 "
    "\001(\tH\001\210"
    "\001\001\022\026\n\tlast_name\030\003 "
    "\001(\tH\002\210\001\001\022\031\n\014phone_numb"
    "er\030\004 \001(\tH\003\210\001\001\022\025\n\010password\030\005 "
    "\001(\tH\004\210\001\001B\r\n\013"
    "_account_idB\r\n\013_first_nameB\014\n\n_last_name"
    "B\017\n\r_phone_numberB\013\n\t_password\"8\n\016Accoun"
    "tRequest\022\027\n\naccount_id\030\001 "
    "\001(\003H\000\210\001\001B\r\n\013_ac"
    "count_id\"e\n\rAdminResponse\022\'\n\006status\030\001 \001("
    "\0162\022.admin."
    "AdminStatusH\000\210\001\001\022\024\n\007message\030\002 "
    "\001(\tH\001\210\001\001B\t\n\007_statusB\n\n\010_message*V\n\013Admin"
    "Status\022\034\n\030ADMIN_STATUS_UNSPECIFIED\020\000\022\023\n\017"
    "ADMIN_STATUS_OK\020\001\022\024\n\020ADMIN_STATUS_ERR\020\0022"
    "\360\001\n\005Admin\0227\n\rCreateAccount\022\016.admin.Accou"
    "nt\032\024.admin.AdminResponse\"\000\0225\n\nGetAccount"
    "\022\025.admin.AccountRequest\032\016.admin.Account\""
    "\000\0227\n\rUpdateAccount\022\016.admin.Account\032\024.adm"
    "in.AdminResponse\"\000\022>\n\rDeleteAccount\022\025.ad"
    "min.AccountRequest\032\024.admin.AdminResponse"
    "\"\000b\006proto3"};
static ::absl::once_flag descriptor_table_admin_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_admin_2eproto = {
    false,
    false,
    730,
    descriptor_table_protodef_admin_2eproto,
    "admin.proto",
    &descriptor_table_admin_2eproto_once,
    nullptr,
    0,
    3,
    schemas,
    file_default_instances,
    TableStruct_admin_2eproto::offsets,
    file_level_enum_descriptors_admin_2eproto,
    file_level_service_descriptors_admin_2eproto,
};
namespace admin {
const ::google::protobuf::EnumDescriptor* PROTOBUF_NONNULL AdminStatus_descriptor() {
  ::google::protobuf::internal::AssignDescriptors(&descriptor_table_admin_2eproto);
  return file_level_enum_descriptors_admin_2eproto[0];
}
PROTOBUF_CONSTINIT const uint32_t AdminStatus_internal_data_[] = {
    196608u,
    0u,
};
// ===================================================================

class Account::_Internal {
 public:
  using HasBits = decltype(::std::declval<Account>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset = 8 * PROTOBUF_FIELD_OFFSET(Account, _impl_._has_bits_);
};

Account::Account(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Account_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:admin.Account)
}
PROTOBUF_NDEBUG_INLINE Account::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::admin::Account& from_msg)
    : _has_bits_{from._has_bits_},
      _cached_size_{0},
      first_name_(arena, from.first_name_),
      last_name_(arena, from.last_name_),
      phone_number_(arena, from.phone_number_),
      password_(arena, from.password_) {}

Account::Account(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Account& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Account_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Account* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.account_id_ = from._impl_.account_id_;

  // @@protoc_insertion_point(copy_constructor:admin.Account)
}
PROTOBUF_NDEBUG_INLINE Account::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : _cached_size_{0},
      first_name_(arena),
      last_name_(arena),
      phone_number_(arena),
      password_(arena) {}

inline void Account::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.account_id_ = {};
}
Account::~Account() {
  // @@protoc_insertion_point(destructor:admin.Account)
  SharedDtor(*this);
}
inline void Account::SharedDtor(MessageLite& self) {
  Account& this_ = static_cast<Account&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.first_name_.Destroy();
  this_._impl_.last_name_.Destroy();
  this_._impl_.phone_number_.Destroy();
  this_._impl_.password_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL
Account::PlacementNew_(const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
                       ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Account(arena);
}
constexpr auto Account::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Account), alignof(Account));
}
constexpr auto Account::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_Account_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &Account::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Account>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Account::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Account>(),
          &Account::ByteSizeLong,
          &Account::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Account, _impl_._cached_size_),
          false,
      },
      &Account::kDescriptorMethods, &descriptor_table_admin_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
    Account_class_data_ = Account::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Account::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Account_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Account_class_data_.tc_table);
  return Account_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<3, 5, 0, 61, 2>
    Account::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(Account, _impl_._has_bits_),
            0,      // no _extensions_
            5, 56,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967264,  // skipmap
            offsetof(decltype(_table_), field_entries),
            5,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            Account_class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::admin::Account>(),  // to_prefetch
#endif                                                       // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            {::_pbi::TcParser::MiniParse, {}},
            // optional int64 account_id = 1;
            {::_pbi::TcParser::SingularVarintNoZag1<::uint64_t,
                                                    offsetof(Account, _impl_.account_id_), 4>(),
             {8, 4, 0, PROTOBUF_FIELD_OFFSET(Account, _impl_.account_id_)}},
            // optional string first_name = 2;
            {::_pbi::TcParser::FastUS1,
             {18, 0, 0, PROTOBUF_FIELD_OFFSET(Account, _impl_.first_name_)}},
            // optional string last_name = 3;
            {::_pbi::TcParser::FastUS1,
             {26, 1, 0, PROTOBUF_FIELD_OFFSET(Account, _impl_.last_name_)}},
            // optional string phone_number = 4;
            {::_pbi::TcParser::FastUS1,
             {34, 2, 0, PROTOBUF_FIELD_OFFSET(Account, _impl_.phone_number_)}},
            // optional string password = 5;
            {::_pbi::TcParser::FastUS1,
             {42, 3, 0, PROTOBUF_FIELD_OFFSET(Account, _impl_.password_)}},
            {::_pbi::TcParser::MiniParse, {}},
            {::_pbi::TcParser::MiniParse, {}},
        }},
        {{65535, 65535}},
        {{
            // optional int64 account_id = 1;
            {PROTOBUF_FIELD_OFFSET(Account, _impl_.account_id_), _Internal::kHasBitsOffset + 4, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
            // optional string first_name = 2;
            {PROTOBUF_FIELD_OFFSET(Account, _impl_.first_name_), _Internal::kHasBitsOffset + 0, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
            // optional string last_name = 3;
            {PROTOBUF_FIELD_OFFSET(Account, _impl_.last_name_), _Internal::kHasBitsOffset + 1, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
            // optional string phone_number = 4;
            {PROTOBUF_FIELD_OFFSET(Account, _impl_.phone_number_), _Internal::kHasBitsOffset + 2, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
            // optional string password = 5;
            {PROTOBUF_FIELD_OFFSET(Account, _impl_.password_), _Internal::kHasBitsOffset + 3, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
        }},
        // no aux_entries
        {{"\15\0\12\11\14\10\0\0"
          "admin.Account"
          "first_name"
          "last_name"
          "phone_number"
          "password"}},
    };
PROTOBUF_NOINLINE void Account::Clear() {
  // @@protoc_insertion_point(message_clear_start:admin.Account)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000000fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _impl_.first_name_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _impl_.last_name_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _impl_.phone_number_.ClearNonDefaultToEmpty();
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _impl_.password_.ClearNonDefaultToEmpty();
    }
  }
  _impl_.account_id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Account::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Account& this_ = static_cast<const Account&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Account::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Account& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:admin.Account)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int64 account_id = 1;
  if ((cached_has_bits & 0x00000010u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
        stream, this_._internal_account_id(), target);
  }

  // optional string first_name = 2;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_first_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()),
        ::google::protobuf::internal::WireFormatLite::SERIALIZE, "admin.Account.first_name");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  // optional string last_name = 3;
  if ((cached_has_bits & 0x00000002u) != 0) {
    const ::std::string& _s = this_._internal_last_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()),
        ::google::protobuf::internal::WireFormatLite::SERIALIZE, "admin.Account.last_name");
    target = stream->WriteStringMaybeAliased(3, _s, target);
  }

  // optional string phone_number = 4;
  if ((cached_has_bits & 0x00000004u) != 0) {
    const ::std::string& _s = this_._internal_phone_number();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()),
        ::google::protobuf::internal::WireFormatLite::SERIALIZE, "admin.Account.phone_number");
    target = stream->WriteStringMaybeAliased(4, _s, target);
  }

  // optional string password = 5;
  if ((cached_has_bits & 0x00000008u) != 0) {
    const ::std::string& _s = this_._internal_password();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()),
        ::google::protobuf::internal::WireFormatLite::SERIALIZE, "admin.Account.password");
    target = stream->WriteStringMaybeAliased(5, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
            ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:admin.Account)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Account::ByteSizeLong(const MessageLite& base) {
  const Account& this_ = static_cast<const Account&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Account::ByteSizeLong() const {
  const Account& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:admin.Account)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    // optional string first_name = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                            this_._internal_first_name());
    }
    // optional string last_name = 3;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::StringSize(this_._internal_last_name());
    }
    // optional string phone_number = 4;
    if ((cached_has_bits & 0x00000004u) != 0) {
      total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                            this_._internal_phone_number());
    }
    // optional string password = 5;
    if ((cached_has_bits & 0x00000008u) != 0) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::StringSize(this_._internal_password());
    }
    // optional int64 account_id = 1;
    if ((cached_has_bits & 0x00000010u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this_._internal_account_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size, &this_._impl_._cached_size_);
}

void Account::MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<Account*>(&to_msg);
  auto& from = static_cast<const Account&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:admin.Account)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x0000001fu) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_first_name(from._internal_first_name());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_internal_set_last_name(from._internal_last_name());
    }
    if ((cached_has_bits & 0x00000004u) != 0) {
      _this->_internal_set_phone_number(from._internal_phone_number());
    }
    if ((cached_has_bits & 0x00000008u) != 0) {
      _this->_internal_set_password(from._internal_password());
    }
    if ((cached_has_bits & 0x00000010u) != 0) {
      _this->_impl_.account_id_ = from._impl_.account_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Account::CopyFrom(const Account& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:admin.Account)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Account::InternalSwap(Account* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.first_name_, &other->_impl_.first_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.last_name_, &other->_impl_.last_name_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.phone_number_, &other->_impl_.phone_number_, arena);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.password_, &other->_impl_.password_, arena);
  swap(_impl_.account_id_, other->_impl_.account_id_);
}

::google::protobuf::Metadata Account::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AccountRequest::_Internal {
 public:
  using HasBits = decltype(::std::declval<AccountRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AccountRequest, _impl_._has_bits_);
};

AccountRequest::AccountRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AccountRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:admin.AccountRequest)
}
AccountRequest::AccountRequest(::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
                               const AccountRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AccountRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE AccountRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : _cached_size_{0} {}

inline void AccountRequest::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.account_id_ = {};
}
AccountRequest::~AccountRequest() {
  // @@protoc_insertion_point(destructor:admin.AccountRequest)
  SharedDtor(*this);
}
inline void AccountRequest::SharedDtor(MessageLite& self) {
  AccountRequest& this_ = static_cast<AccountRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL
AccountRequest::PlacementNew_(const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
                              ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AccountRequest(arena);
}
constexpr auto AccountRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(sizeof(AccountRequest),
                                                                alignof(AccountRequest));
}
constexpr auto AccountRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AccountRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &AccountRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AccountRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AccountRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AccountRequest>(),
          &AccountRequest::ByteSizeLong,
          &AccountRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AccountRequest, _impl_._cached_size_),
          false,
      },
      &AccountRequest::kDescriptorMethods, &descriptor_table_admin_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
    AccountRequest_class_data_ = AccountRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AccountRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AccountRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AccountRequest_class_data_.tc_table);
  return AccountRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
    AccountRequest::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(AccountRequest, _impl_._has_bits_),
            0,     // no _extensions_
            1, 0,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967294,  // skipmap
            offsetof(decltype(_table_), field_entries),
            1,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            AccountRequest_class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::admin::AccountRequest>(),  // to_prefetch
#endif                                                              // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // optional int64 account_id = 1;
            {::_pbi::TcParser::SingularVarintNoZag1<
                 ::uint64_t, offsetof(AccountRequest, _impl_.account_id_), 0>(),
             {8, 0, 0, PROTOBUF_FIELD_OFFSET(AccountRequest, _impl_.account_id_)}},
        }},
        {{65535, 65535}},
        {{
            // optional int64 account_id = 1;
            {PROTOBUF_FIELD_OFFSET(AccountRequest, _impl_.account_id_),
             _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
        }},
        // no aux_entries
        {{}},
    };
PROTOBUF_NOINLINE void AccountRequest::Clear() {
  // @@protoc_insertion_point(message_clear_start:admin.AccountRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  _impl_.account_id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AccountRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AccountRequest& this_ = static_cast<const AccountRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AccountRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AccountRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:admin.AccountRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int64 account_id = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt64ToArrayWithField<1>(
        stream, this_._internal_account_id(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
            ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:admin.AccountRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AccountRequest::ByteSizeLong(const MessageLite& base) {
  const AccountRequest& this_ = static_cast<const AccountRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AccountRequest::ByteSizeLong() const {
  const AccountRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:admin.AccountRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  {
    // optional int64 account_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(this_._internal_account_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size, &this_._impl_._cached_size_);
}

void AccountRequest::MergeImpl(::google::protobuf::MessageLite& to_msg,
                               const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AccountRequest*>(&to_msg);
  auto& from = static_cast<const AccountRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:admin.AccountRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _this->_impl_.account_id_ = from._impl_.account_id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AccountRequest::CopyFrom(const AccountRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:admin.AccountRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AccountRequest::InternalSwap(AccountRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.account_id_, other->_impl_.account_id_);
}

::google::protobuf::Metadata AccountRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class AdminResponse::_Internal {
 public:
  using HasBits = decltype(::std::declval<AdminResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(AdminResponse, _impl_._has_bits_);
};

AdminResponse::AdminResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AdminResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:admin.AdminResponse)
}
PROTOBUF_NDEBUG_INLINE AdminResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::admin::AdminResponse& from_msg)
    : _has_bits_{from._has_bits_}, _cached_size_{0}, message_(arena, from.message_) {}

AdminResponse::AdminResponse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
                             const AdminResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, AdminResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  AdminResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  _impl_.status_ = from._impl_.status_;

  // @@protoc_insertion_point(copy_constructor:admin.AdminResponse)
}
PROTOBUF_NDEBUG_INLINE AdminResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : _cached_size_{0}, message_(arena) {}

inline void AdminResponse::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.status_ = {};
}
AdminResponse::~AdminResponse() {
  // @@protoc_insertion_point(destructor:admin.AdminResponse)
  SharedDtor(*this);
}
inline void AdminResponse::SharedDtor(MessageLite& self) {
  AdminResponse& this_ = static_cast<AdminResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.message_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL
AdminResponse::PlacementNew_(const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
                             ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) AdminResponse(arena);
}
constexpr auto AdminResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(AdminResponse),
                                                                alignof(AdminResponse));
}
constexpr auto AdminResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_AdminResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &AdminResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<AdminResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &AdminResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<AdminResponse>(),
          &AdminResponse::ByteSizeLong,
          &AdminResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(AdminResponse, _impl_._cached_size_),
          false,
      },
      &AdminResponse::kDescriptorMethods, &descriptor_table_admin_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::internal::ClassDataFull
    AdminResponse_class_data_ = AdminResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
AdminResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&AdminResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(AdminResponse_class_data_.tc_table);
  return AdminResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<1, 2, 0, 35, 2>
    AdminResponse::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(AdminResponse, _impl_._has_bits_),
            0,     // no _extensions_
            2, 8,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967292,  // skipmap
            offsetof(decltype(_table_), field_entries),
            2,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            AdminResponse_class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<::admin::AdminResponse>(),  // to_prefetch
#endif                                                             // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // optional string message = 2;
            {::_pbi::TcParser::FastUS1,
             {18, 0, 0, PROTOBUF_FIELD_OFFSET(AdminResponse, _impl_.message_)}},
            // optional .admin.AdminStatus status = 1;
            {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t,
                                                    offsetof(AdminResponse, _impl_.status_), 1>(),
             {8, 1, 0, PROTOBUF_FIELD_OFFSET(AdminResponse, _impl_.status_)}},
        }},
        {{65535, 65535}},
        {{
            // optional .admin.AdminStatus status = 1;
            {PROTOBUF_FIELD_OFFSET(AdminResponse, _impl_.status_), _Internal::kHasBitsOffset + 1, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
            // optional string message = 2;
            {PROTOBUF_FIELD_OFFSET(AdminResponse, _impl_.message_), _Internal::kHasBitsOffset + 0,
             0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
        }},
        // no aux_entries
        {{"\23\0\7\0\0\0\0\0"
          "admin.AdminResponse"
          "message"}},
    };
PROTOBUF_NOINLINE void AdminResponse::Clear() {
  // @@protoc_insertion_point(message_clear_start:admin.AdminResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.message_.ClearNonDefaultToEmpty();
  }
  _impl_.status_ = 0;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL AdminResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const AdminResponse& this_ = static_cast<const AdminResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL AdminResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const AdminResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:admin.AdminResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional .admin.AdminStatus status = 1;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteEnumToArray(1, this_._internal_status(), target);
  }

  // optional string message = 2;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_message();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()),
        ::google::protobuf::internal::WireFormatLite::SERIALIZE, "admin.AdminResponse.message");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(
            ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:admin.AdminResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t AdminResponse::ByteSizeLong(const MessageLite& base) {
  const AdminResponse& this_ = static_cast<const AdminResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t AdminResponse::ByteSizeLong() const {
  const AdminResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:admin.AdminResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // optional string message = 2;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::StringSize(this_._internal_message());
    }
    // optional .admin.AdminStatus status = 1;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += 1 + ::_pbi::WireFormatLite::EnumSize(this_._internal_status());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size, &this_._impl_._cached_size_);
}

void AdminResponse::MergeImpl(::google::protobuf::MessageLite& to_msg,
                              const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<AdminResponse*>(&to_msg);
  auto& from = static_cast<const AdminResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:admin.AdminResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_internal_set_message(from._internal_message());
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.status_ = from._impl_.status_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void AdminResponse::CopyFrom(const AdminResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:admin.AdminResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void AdminResponse::InternalSwap(AdminResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.message_, &other->_impl_.message_, arena);
  swap(_impl_.status_, other->_impl_.status_);
}

::google::protobuf::Metadata AdminResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace admin
namespace google {
namespace protobuf {}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type _static_init2_ [[maybe_unused]] =
    (::_pbi::AddDescriptors(&descriptor_table_admin_2eproto), ::std::false_type{});
#include "google/protobuf/port_undef.inc"
