// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: helloworld.proto
#ifndef GRPC_helloworld_2eproto__INCLUDED
#define GRPC_helloworld_2eproto__INCLUDED

#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/impl/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/server_context.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/support/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

#include <functional>
#include <grpcpp/ports_def.inc>

#include "helloworld.pb.h"

namespace helloworld {

class Greeter final {
 public:
  static constexpr char const* service_full_name() {
    return "helloworld.Greeter";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    virtual ::grpc::Status HelloWorld(
        ::grpc::ClientContext* context,
        const ::helloworld::HelloWorldRequest& request,
        ::helloworld::HelloWorldResponse* response) = 0;
    std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<
        ::helloworld::HelloWorldResponse>>
    AsyncHelloWorld(::grpc::ClientContext* context,
                    const ::helloworld::HelloWorldRequest& request,
                    ::grpc::CompletionQueue* cq) {
      return std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<
          ::helloworld::HelloWorldResponse>>(
          AsyncHelloWorldRaw(context, request, cq));
    }
    std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<
        ::helloworld::HelloWorldResponse>>
    PrepareAsyncHelloWorld(::grpc::ClientContext* context,
                           const ::helloworld::HelloWorldRequest& request,
                           ::grpc::CompletionQueue* cq) {
      return std::unique_ptr<::grpc::ClientAsyncResponseReaderInterface<
          ::helloworld::HelloWorldResponse>>(
          PrepareAsyncHelloWorldRaw(context, request, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void HelloWorld(::grpc::ClientContext* context,
                              const ::helloworld::HelloWorldRequest* request,
                              ::helloworld::HelloWorldResponse* response,
                              std::function<void(::grpc::Status)>) = 0;
      virtual void HelloWorld(::grpc::ClientContext* context,
                              const ::helloworld::HelloWorldRequest* request,
                              ::helloworld::HelloWorldResponse* response,
                              ::grpc::ClientUnaryReactor* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }

   private:
    virtual ::grpc::ClientAsyncResponseReaderInterface<
        ::helloworld::HelloWorldResponse>*
    AsyncHelloWorldRaw(::grpc::ClientContext* context,
                       const ::helloworld::HelloWorldRequest& request,
                       ::grpc::CompletionQueue* cq) = 0;
    virtual ::grpc::ClientAsyncResponseReaderInterface<
        ::helloworld::HelloWorldResponse>*
    PrepareAsyncHelloWorldRaw(::grpc::ClientContext* context,
                              const ::helloworld::HelloWorldRequest& request,
                              ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr<::grpc::ChannelInterface>& channel,
         const ::grpc::StubOptions& options = ::grpc::StubOptions());
    ::grpc::Status HelloWorld(
        ::grpc::ClientContext* context,
        const ::helloworld::HelloWorldRequest& request,
        ::helloworld::HelloWorldResponse* response) override;
    std::unique_ptr<
        ::grpc::ClientAsyncResponseReader<::helloworld::HelloWorldResponse>>
    AsyncHelloWorld(::grpc::ClientContext* context,
                    const ::helloworld::HelloWorldRequest& request,
                    ::grpc::CompletionQueue* cq) {
      return std::unique_ptr<
          ::grpc::ClientAsyncResponseReader<::helloworld::HelloWorldResponse>>(
          AsyncHelloWorldRaw(context, request, cq));
    }
    std::unique_ptr<
        ::grpc::ClientAsyncResponseReader<::helloworld::HelloWorldResponse>>
    PrepareAsyncHelloWorld(::grpc::ClientContext* context,
                           const ::helloworld::HelloWorldRequest& request,
                           ::grpc::CompletionQueue* cq) {
      return std::unique_ptr<
          ::grpc::ClientAsyncResponseReader<::helloworld::HelloWorldResponse>>(
          PrepareAsyncHelloWorldRaw(context, request, cq));
    }
    class async final : public StubInterface::async_interface {
     public:
      void HelloWorld(::grpc::ClientContext* context,
                      const ::helloworld::HelloWorldRequest* request,
                      ::helloworld::HelloWorldResponse* response,
                      std::function<void(::grpc::Status)>) override;
      void HelloWorld(::grpc::ClientContext* context,
                      const ::helloworld::HelloWorldRequest* request,
                      ::helloworld::HelloWorldResponse* response,
                      ::grpc::ClientUnaryReactor* reactor) override;

     private:
      friend class Stub;
      explicit async(Stub* stub) : stub_(stub) {}
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr<::grpc::ChannelInterface> channel_;
    class async async_stub_ {
      this
    };
    ::grpc::ClientAsyncResponseReader<::helloworld::HelloWorldResponse>*
    AsyncHelloWorldRaw(::grpc::ClientContext* context,
                       const ::helloworld::HelloWorldRequest& request,
                       ::grpc::CompletionQueue* cq) override;
    ::grpc::ClientAsyncResponseReader<::helloworld::HelloWorldResponse>*
    PrepareAsyncHelloWorldRaw(::grpc::ClientContext* context,
                              const ::helloworld::HelloWorldRequest& request,
                              ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_HelloWorld_;
  };
  static std::unique_ptr<Stub> NewStub(
      const std::shared_ptr<::grpc::ChannelInterface>& channel,
      const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status HelloWorld(
        ::grpc::ServerContext* context,
        const ::helloworld::HelloWorldRequest* request,
        ::helloworld::HelloWorldResponse* response);
  };
  template <class BaseClass>
  class WithAsyncMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}

   public:
    WithAsyncMethod_HelloWorld() { ::grpc::Service::MarkMethodAsync(0); }
    ~WithAsyncMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HelloWorld(
        ::grpc::ServerContext* /*context*/,
        const ::helloworld::HelloWorldRequest* /*request*/,
        ::helloworld::HelloWorldResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHelloWorld(
        ::grpc::ServerContext* context,
        ::helloworld::HelloWorldRequest* request,
        ::grpc::ServerAsyncResponseWriter<::helloworld::HelloWorldResponse>*
            response,
        ::grpc::CompletionQueue* new_call_cq,
        ::grpc::ServerCompletionQueue* notification_cq, void* tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response,
                                         new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_HelloWorld<Service> AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}

   public:
    WithCallbackMethod_HelloWorld() {
      ::grpc::Service::MarkMethodCallback(
          0, new ::grpc::internal::CallbackUnaryHandler<
                 ::helloworld::HelloWorldRequest,
                 ::helloworld::HelloWorldResponse>(
                 [this](::grpc::CallbackServerContext* context,
                        const ::helloworld::HelloWorldRequest* request,
                        ::helloworld::HelloWorldResponse* response) {
                   return this->HelloWorld(context, request, response);
                 }));
    }
    void SetMessageAllocatorFor_HelloWorld(
        ::grpc::MessageAllocator<::helloworld::HelloWorldRequest,
                                 ::helloworld::HelloWorldResponse>* allocator) {
      ::grpc::internal::MethodHandler* const handler =
          ::grpc::Service::GetHandler(0);
      static_cast<::grpc::internal::CallbackUnaryHandler<
          ::helloworld::HelloWorldRequest, ::helloworld::HelloWorldResponse>*>(
          handler)
          ->SetMessageAllocator(allocator);
    }
    ~WithCallbackMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HelloWorld(
        ::grpc::ServerContext* /*context*/,
        const ::helloworld::HelloWorldRequest* /*request*/,
        ::helloworld::HelloWorldResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HelloWorld(
        ::grpc::CallbackServerContext* /*context*/,
        const ::helloworld::HelloWorldRequest* /*request*/,
        ::helloworld::HelloWorldResponse* /*response*/) {
      return nullptr;
    }
  };
  typedef WithCallbackMethod_HelloWorld<Service> CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}

   public:
    WithGenericMethod_HelloWorld() { ::grpc::Service::MarkMethodGeneric(0); }
    ~WithGenericMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HelloWorld(
        ::grpc::ServerContext* /*context*/,
        const ::helloworld::HelloWorldRequest* /*request*/,
        ::helloworld::HelloWorldResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}

   public:
    WithRawMethod_HelloWorld() { ::grpc::Service::MarkMethodRaw(0); }
    ~WithRawMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HelloWorld(
        ::grpc::ServerContext* /*context*/,
        const ::helloworld::HelloWorldRequest* /*request*/,
        ::helloworld::HelloWorldResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestHelloWorld(
        ::grpc::ServerContext* context, ::grpc::ByteBuffer* request,
        ::grpc::ServerAsyncResponseWriter<::grpc::ByteBuffer>* response,
        ::grpc::CompletionQueue* new_call_cq,
        ::grpc::ServerCompletionQueue* notification_cq, void* tag) {
      ::grpc::Service::RequestAsyncUnary(0, context, request, response,
                                         new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}

   public:
    WithRawCallbackMethod_HelloWorld() {
      ::grpc::Service::MarkMethodRawCallback(
          0, new ::grpc::internal::CallbackUnaryHandler<::grpc::ByteBuffer,
                                                        ::grpc::ByteBuffer>(
                 [this](::grpc::CallbackServerContext* context,
                        const ::grpc::ByteBuffer* request,
                        ::grpc::ByteBuffer* response) {
                   return this->HelloWorld(context, request, response);
                 }));
    }
    ~WithRawCallbackMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status HelloWorld(
        ::grpc::ServerContext* /*context*/,
        const ::helloworld::HelloWorldRequest* /*request*/,
        ::helloworld::HelloWorldResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerUnaryReactor* HelloWorld(
        ::grpc::CallbackServerContext* /*context*/,
        const ::grpc::ByteBuffer* /*request*/,
        ::grpc::ByteBuffer* /*response*/) {
      return nullptr;
    }
  };
  template <class BaseClass>
  class WithStreamedUnaryMethod_HelloWorld : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}

   public:
    WithStreamedUnaryMethod_HelloWorld() {
      ::grpc::Service::MarkMethodStreamed(
          0,
          new ::grpc::internal::StreamedUnaryHandler<
              ::helloworld::HelloWorldRequest,
              ::helloworld::HelloWorldResponse>(
              [this](
                  ::grpc::ServerContext* context,
                  ::grpc::ServerUnaryStreamer<::helloworld::HelloWorldRequest,
                                              ::helloworld::HelloWorldResponse>*
                      streamer) {
                return this->StreamedHelloWorld(context, streamer);
              }));
    }
    ~WithStreamedUnaryMethod_HelloWorld() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable regular version of this method
    ::grpc::Status HelloWorld(
        ::grpc::ServerContext* /*context*/,
        const ::helloworld::HelloWorldRequest* /*request*/,
        ::helloworld::HelloWorldResponse* /*response*/) override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    // replace default version of method with streamed unary
    virtual ::grpc::Status StreamedHelloWorld(
        ::grpc::ServerContext* context,
        ::grpc::ServerUnaryStreamer<::helloworld::HelloWorldRequest,
                                    ::helloworld::HelloWorldResponse>*
            server_unary_streamer) = 0;
  };
  typedef WithStreamedUnaryMethod_HelloWorld<Service> StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef WithStreamedUnaryMethod_HelloWorld<Service> StreamedService;
};

}  // namespace helloworld

#include <grpcpp/ports_undef.inc>
#endif  // GRPC_helloworld_2eproto__INCLUDED
