// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: matching.proto
// Protobuf C++ Version: 6.31.0

#include "matching.pb.h"

#include <algorithm>
#include <type_traits>

#include "google/protobuf/descriptor.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/wire_format_lite.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace matching {

inline constexpr ListMatchesRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
    : _cached_size_{0}, account_id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR ListMatchesRequest::ListMatchesRequest(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ListMatchesRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ListMatchesRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListMatchesRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListMatchesRequestDefaultTypeInternal() {}
  union {
    ListMatchesRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListMatchesRequestDefaultTypeInternal
        _ListMatchesRequest_default_instance_;

inline constexpr CheckMatchResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
    : _cached_size_{0}, matched_{false} {}

template <typename>
PROTOBUF_CONSTEXPR CheckMatchResponse::CheckMatchResponse(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CheckMatchResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CheckMatchResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckMatchResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckMatchResponseDefaultTypeInternal() {}
  union {
    CheckMatchResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckMatchResponseDefaultTypeInternal
        _CheckMatchResponse_default_instance_;

inline constexpr CheckMatchRequest::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
    : _cached_size_{0},
      checker_account_id_{::int64_t{0}},
      checked_account_id_{::int64_t{0}} {}

template <typename>
PROTOBUF_CONSTEXPR CheckMatchRequest::CheckMatchRequest(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(CheckMatchRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct CheckMatchRequestDefaultTypeInternal {
  PROTOBUF_CONSTEXPR CheckMatchRequestDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~CheckMatchRequestDefaultTypeInternal() {}
  union {
    CheckMatchRequest _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 CheckMatchRequestDefaultTypeInternal
        _CheckMatchRequest_default_instance_;

inline constexpr ListMatchesResponse::Impl_::Impl_(
    ::_pbi::ConstantInitialized) noexcept
    : _cached_size_{0},
      profile_{},
      page_token_(&::google::protobuf::internal::fixed_address_empty_string,
                  ::_pbi::ConstantInitialized()) {}

template <typename>
PROTOBUF_CONSTEXPR ListMatchesResponse::ListMatchesResponse(
    ::_pbi::ConstantInitialized)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(ListMatchesResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(::_pbi::ConstantInitialized()) {
}
struct ListMatchesResponseDefaultTypeInternal {
  PROTOBUF_CONSTEXPR ListMatchesResponseDefaultTypeInternal()
      : _instance(::_pbi::ConstantInitialized{}) {}
  ~ListMatchesResponseDefaultTypeInternal() {}
  union {
    ListMatchesResponse _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 ListMatchesResponseDefaultTypeInternal
        _ListMatchesResponse_default_instance_;
}  // namespace matching
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL*
    PROTOBUF_NULLABLE file_level_enum_descriptors_matching_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL*
    PROTOBUF_NULLABLE file_level_service_descriptors_matching_2eproto = nullptr;
const ::uint32_t
    TableStruct_matching_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081,  // bitmap
        PROTOBUF_FIELD_OFFSET(::matching::CheckMatchRequest, _impl_._has_bits_),
        5,  // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::matching::CheckMatchRequest,
                              _impl_.checker_account_id_),
        PROTOBUF_FIELD_OFFSET(::matching::CheckMatchRequest,
                              _impl_.checked_account_id_),
        0,
        1,
        0x081,  // bitmap
        PROTOBUF_FIELD_OFFSET(::matching::CheckMatchResponse,
                              _impl_._has_bits_),
        4,  // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::matching::CheckMatchResponse, _impl_.matched_),
        0,
        0x081,  // bitmap
        PROTOBUF_FIELD_OFFSET(::matching::ListMatchesRequest,
                              _impl_._has_bits_),
        4,  // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::matching::ListMatchesRequest,
                              _impl_.account_id_),
        0,
        0x081,  // bitmap
        PROTOBUF_FIELD_OFFSET(::matching::ListMatchesResponse,
                              _impl_._has_bits_),
        5,  // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::matching::ListMatchesResponse, _impl_.profile_),
        PROTOBUF_FIELD_OFFSET(::matching::ListMatchesResponse,
                              _impl_.page_token_),
        ~0u,
        0,
};

static const ::_pbi::MigrationSchema schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    {0, sizeof(::matching::CheckMatchRequest)},
    {7, sizeof(::matching::CheckMatchResponse)},
    {12, sizeof(::matching::ListMatchesRequest)},
    {17, sizeof(::matching::ListMatchesResponse)},
};
static const ::_pb::Message* PROTOBUF_NONNULL const file_default_instances[] = {
    &::matching::_CheckMatchRequest_default_instance_._instance,
    &::matching::_CheckMatchResponse_default_instance_._instance,
    &::matching::_ListMatchesRequest_default_instance_._instance,
    &::matching::_ListMatchesResponse_default_instance_._instance,
};
const char descriptor_table_protodef_matching_2eproto
    [] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        "\n\016matching.proto\022\010matching\032\rprofile.prot"
        "o\"\203\001\n\021CheckMatchRequest\022\037\n\022checker_accou"
        "nt_id\030\001 "
        "\001(\003H\000\210\001\001\022\037\n\022checked_account_id\030\002"
        " \001(\003H\001\210\001\001B\025\n\023_checker_account_idB\025\n\023_"
        "che"
        "cked_account_id\"6\n\022CheckMatchResponse\022\024\n"
        "\007matched\030\001 "
        "\001(\010H\000\210\001\001B\n\n\010_matched\"<\n\022ListM"
        "atchesRequest\022\027\n\naccount_id\030\001 "
        "\001(\003H\000\210\001\001B\r"
        "\n\013_account_id\"d\n\023ListMatchesResponse\022%\n\007"
        "profile\030\001 \003(\0132\024.profile.ProfileCard\022\027\n\np"
        "age_token\030\002 "
        "\001(\tH\000\210\001\001B\r\n\013_page_token2\243\001\n\010"
        "Matching\022I\n\nCheckMatch\022\033.matching.CheckM"
        "atchRequest\032\034.matching.CheckMatchRespons"
        "e\"\000\022L\n\013ListMatches\022\034.matching.ListMatche"
        "sRequest\032\035.matching.ListMatchesResponse\""
        "\000b\006proto3"};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_matching_2eproto_deps[1] = {
        &::descriptor_table_profile_2eproto,
};
static ::absl::once_flag descriptor_table_matching_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable
    descriptor_table_matching_2eproto = {
        false,
        false,
        569,
        descriptor_table_protodef_matching_2eproto,
        "matching.proto",
        &descriptor_table_matching_2eproto_once,
        descriptor_table_matching_2eproto_deps,
        1,
        4,
        schemas,
        file_default_instances,
        TableStruct_matching_2eproto::offsets,
        file_level_enum_descriptors_matching_2eproto,
        file_level_service_descriptors_matching_2eproto,
};
namespace matching {
// ===================================================================

class CheckMatchRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CheckMatchRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CheckMatchRequest, _impl_._has_bits_);
};

CheckMatchRequest::CheckMatchRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CheckMatchRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:matching.CheckMatchRequest)
}
CheckMatchRequest::CheckMatchRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CheckMatchRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CheckMatchRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CheckMatchRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : _cached_size_{0} {}

inline void CheckMatchRequest::SharedCtor(
    ::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(
      reinterpret_cast<char*>(&_impl_) + offsetof(Impl_, checker_account_id_),
      0,
      offsetof(Impl_, checked_account_id_) -
          offsetof(Impl_, checker_account_id_) +
          sizeof(Impl_::checked_account_id_));
}
CheckMatchRequest::~CheckMatchRequest() {
  // @@protoc_insertion_point(destructor:matching.CheckMatchRequest)
  SharedDtor(*this);
}
inline void CheckMatchRequest::SharedDtor(MessageLite& self) {
  CheckMatchRequest& this_ = static_cast<CheckMatchRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CheckMatchRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CheckMatchRequest(arena);
}
constexpr auto CheckMatchRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(
      sizeof(CheckMatchRequest), alignof(CheckMatchRequest));
}
constexpr auto CheckMatchRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CheckMatchRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CheckMatchRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CheckMatchRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CheckMatchRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CheckMatchRequest>(),
          &CheckMatchRequest::ByteSizeLong,
          &CheckMatchRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CheckMatchRequest, _impl_._cached_size_),
          false,
      },
      &CheckMatchRequest::kDescriptorMethods,
      &descriptor_table_matching_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::
    internal::ClassDataFull CheckMatchRequest_class_data_ =
        CheckMatchRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData*
    PROTOBUF_NONNULL
    CheckMatchRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(
      &CheckMatchRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      CheckMatchRequest_class_data_.tc_table);
  return CheckMatchRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<
    1, 2, 0, 0, 2>
    CheckMatchRequest::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(CheckMatchRequest, _impl_._has_bits_),
            0,     // no _extensions_
            2, 8,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967292,  // skipmap
            offsetof(decltype(_table_), field_entries),
            2,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            CheckMatchRequest_class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::matching::CheckMatchRequest>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // optional int64 checked_account_id = 2;
            {::_pbi::TcParser::SingularVarintNoZag1<
                 ::uint64_t,
                 offsetof(CheckMatchRequest, _impl_.checked_account_id_), 1>(),
             {16, 1, 0,
              PROTOBUF_FIELD_OFFSET(CheckMatchRequest,
                                    _impl_.checked_account_id_)}},
            // optional int64 checker_account_id = 1;
            {::_pbi::TcParser::SingularVarintNoZag1<
                 ::uint64_t,
                 offsetof(CheckMatchRequest, _impl_.checker_account_id_), 0>(),
             {8, 0, 0,
              PROTOBUF_FIELD_OFFSET(CheckMatchRequest,
                                    _impl_.checker_account_id_)}},
        }},
        {{65535, 65535}},
        {{
            // optional int64 checker_account_id = 1;
            {PROTOBUF_FIELD_OFFSET(CheckMatchRequest,
                                   _impl_.checker_account_id_),
             _Internal::kHasBitsOffset + 0, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
            // optional int64 checked_account_id = 2;
            {PROTOBUF_FIELD_OFFSET(CheckMatchRequest,
                                   _impl_.checked_account_id_),
             _Internal::kHasBitsOffset + 1, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
        }},
        // no aux_entries
        {{}},
    };
PROTOBUF_NOINLINE void CheckMatchRequest::Clear() {
  // @@protoc_insertion_point(message_clear_start:matching.CheckMatchRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    ::memset(&_impl_.checker_account_id_, 0,
             static_cast<::size_t>(
                 reinterpret_cast<char*>(&_impl_.checked_account_id_) -
                 reinterpret_cast<char*>(&_impl_.checker_account_id_)) +
                 sizeof(_impl_.checked_account_id_));
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CheckMatchRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base,
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CheckMatchRequest& this_ = static_cast<const CheckMatchRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CheckMatchRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL
        stream) const {
  const CheckMatchRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:matching.CheckMatchRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int64 checker_account_id = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(
            stream, this_._internal_checker_account_id(), target);
  }

  // optional int64 checked_account_id = 2;
  if ((cached_has_bits & 0x00000002u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<2>(
            stream, this_._internal_checked_account_id(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:matching.CheckMatchRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CheckMatchRequest::ByteSizeLong(const MessageLite& base) {
  const CheckMatchRequest& this_ = static_cast<const CheckMatchRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CheckMatchRequest::ByteSizeLong() const {
  const CheckMatchRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:matching.CheckMatchRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    // optional int64 checker_account_id = 1;
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_checker_account_id());
    }
    // optional int64 checked_account_id = 2;
    if ((cached_has_bits & 0x00000002u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_checked_account_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CheckMatchRequest::MergeImpl(
    ::google::protobuf::MessageLite& to_msg,
    const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CheckMatchRequest*>(&to_msg);
  auto& from = static_cast<const CheckMatchRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:matching.CheckMatchRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000003u) != 0) {
    if ((cached_has_bits & 0x00000001u) != 0) {
      _this->_impl_.checker_account_id_ = from._impl_.checker_account_id_;
    }
    if ((cached_has_bits & 0x00000002u) != 0) {
      _this->_impl_.checked_account_id_ = from._impl_.checked_account_id_;
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CheckMatchRequest::CopyFrom(const CheckMatchRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:matching.CheckMatchRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CheckMatchRequest::InternalSwap(
    CheckMatchRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(CheckMatchRequest, _impl_.checked_account_id_) +
      sizeof(CheckMatchRequest::_impl_.checked_account_id_) -
      PROTOBUF_FIELD_OFFSET(CheckMatchRequest, _impl_.checker_account_id_)>(
      reinterpret_cast<char*>(&_impl_.checker_account_id_),
      reinterpret_cast<char*>(&other->_impl_.checker_account_id_));
}

::google::protobuf::Metadata CheckMatchRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class CheckMatchResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<CheckMatchResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(CheckMatchResponse, _impl_._has_bits_);
};

CheckMatchResponse::CheckMatchResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena,
                                  CheckMatchResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:matching.CheckMatchResponse)
}
CheckMatchResponse::CheckMatchResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const CheckMatchResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, CheckMatchResponse_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE CheckMatchResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : _cached_size_{0} {}

inline void CheckMatchResponse::SharedCtor(
    ::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.matched_ = {};
}
CheckMatchResponse::~CheckMatchResponse() {
  // @@protoc_insertion_point(destructor:matching.CheckMatchResponse)
  SharedDtor(*this);
}
inline void CheckMatchResponse::SharedDtor(MessageLite& self) {
  CheckMatchResponse& this_ = static_cast<CheckMatchResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL CheckMatchResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) CheckMatchResponse(arena);
}
constexpr auto CheckMatchResponse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(
      sizeof(CheckMatchResponse), alignof(CheckMatchResponse));
}
constexpr auto CheckMatchResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_CheckMatchResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &CheckMatchResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<CheckMatchResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &CheckMatchResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<CheckMatchResponse>(),
          &CheckMatchResponse::ByteSizeLong,
          &CheckMatchResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(CheckMatchResponse, _impl_._cached_size_),
          false,
      },
      &CheckMatchResponse::kDescriptorMethods,
      &descriptor_table_matching_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::
    internal::ClassDataFull CheckMatchResponse_class_data_ =
        CheckMatchResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData*
    PROTOBUF_NONNULL
    CheckMatchResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(
      &CheckMatchResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      CheckMatchResponse_class_data_.tc_table);
  return CheckMatchResponse_class_data_.base();
}
PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<0, 1, 0, 0, 2>
        CheckMatchResponse::_table_ = {
            {
                PROTOBUF_FIELD_OFFSET(CheckMatchResponse, _impl_._has_bits_),
                0,     // no _extensions_
                1, 0,  // max_field_number, fast_idx_mask
                offsetof(decltype(_table_), field_lookup_table),
                4294967294,  // skipmap
                offsetof(decltype(_table_), field_entries),
                1,                                         // num_field_entries
                0,                                         // num_aux_entries
                offsetof(decltype(_table_), field_names),  // no aux_entries
                CheckMatchResponse_class_data_.base(),
                nullptr,                            // post_loop_handler
                ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
                ::_pbi::TcParser::GetTable<
                    ::matching::CheckMatchResponse>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
            },
            {{
                // optional bool matched = 1;
                {::_pbi::TcParser::SingularVarintNoZag1<
                     bool, offsetof(CheckMatchResponse, _impl_.matched_), 0>(),
                 {8, 0, 0,
                  PROTOBUF_FIELD_OFFSET(CheckMatchResponse, _impl_.matched_)}},
            }},
            {{65535, 65535}},
            {{
                // optional bool matched = 1;
                {PROTOBUF_FIELD_OFFSET(CheckMatchResponse, _impl_.matched_),
                 _Internal::kHasBitsOffset + 0, 0,
                 (0 | ::_fl::kFcOptional | ::_fl::kBool)},
            }},
            // no aux_entries
            {{}},
        };
PROTOBUF_NOINLINE void CheckMatchResponse::Clear() {
  // @@protoc_insertion_point(message_clear_start:matching.CheckMatchResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  _impl_.matched_ = false;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL CheckMatchResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base,
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const CheckMatchResponse& this_ =
      static_cast<const CheckMatchResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL CheckMatchResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL
        stream) const {
  const CheckMatchResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:matching.CheckMatchResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional bool matched = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteBoolToArray(
        1, this_._internal_matched(), target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:matching.CheckMatchResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t CheckMatchResponse::ByteSizeLong(const MessageLite& base) {
  const CheckMatchResponse& this_ =
      static_cast<const CheckMatchResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t CheckMatchResponse::ByteSizeLong() const {
  const CheckMatchResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:matching.CheckMatchResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  total_size += static_cast<bool>(0x00000001u & cached_has_bits) * 2;
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void CheckMatchResponse::MergeImpl(
    ::google::protobuf::MessageLite& to_msg,
    const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<CheckMatchResponse*>(&to_msg);
  auto& from = static_cast<const CheckMatchResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:matching.CheckMatchResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _this->_impl_.matched_ = from._impl_.matched_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void CheckMatchResponse::CopyFrom(const CheckMatchResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:matching.CheckMatchResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void CheckMatchResponse::InternalSwap(
    CheckMatchResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.matched_, other->_impl_.matched_);
}

::google::protobuf::Metadata CheckMatchResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ListMatchesRequest::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ListMatchesRequest>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ListMatchesRequest, _impl_._has_bits_);
};

ListMatchesRequest::ListMatchesRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena,
                                  ListMatchesRequest_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:matching.ListMatchesRequest)
}
ListMatchesRequest::ListMatchesRequest(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ListMatchesRequest& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, ListMatchesRequest_class_data_.base()),
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena),
#endif  // PROTOBUF_CUSTOM_VTABLE
      _impl_(from._impl_) {
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}
PROTOBUF_NDEBUG_INLINE ListMatchesRequest::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : _cached_size_{0} {}

inline void ListMatchesRequest::SharedCtor(
    ::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  _impl_.account_id_ = {};
}
ListMatchesRequest::~ListMatchesRequest() {
  // @@protoc_insertion_point(destructor:matching.ListMatchesRequest)
  SharedDtor(*this);
}
inline void ListMatchesRequest::SharedDtor(MessageLite& self) {
  ListMatchesRequest& this_ = static_cast<ListMatchesRequest&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ListMatchesRequest::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ListMatchesRequest(arena);
}
constexpr auto ListMatchesRequest::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::ZeroInit(
      sizeof(ListMatchesRequest), alignof(ListMatchesRequest));
}
constexpr auto ListMatchesRequest::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ListMatchesRequest_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ListMatchesRequest::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ListMatchesRequest>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ListMatchesRequest::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ListMatchesRequest>(),
          &ListMatchesRequest::ByteSizeLong,
          &ListMatchesRequest::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ListMatchesRequest, _impl_._cached_size_),
          false,
      },
      &ListMatchesRequest::kDescriptorMethods,
      &descriptor_table_matching_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::
    internal::ClassDataFull ListMatchesRequest_class_data_ =
        ListMatchesRequest::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData*
    PROTOBUF_NONNULL
    ListMatchesRequest::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(
      &ListMatchesRequest_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ListMatchesRequest_class_data_.tc_table);
  return ListMatchesRequest_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<
    0, 1, 0, 0, 2>
    ListMatchesRequest::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(ListMatchesRequest, _impl_._has_bits_),
            0,     // no _extensions_
            1, 0,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967294,  // skipmap
            offsetof(decltype(_table_), field_entries),
            1,                                         // num_field_entries
            0,                                         // num_aux_entries
            offsetof(decltype(_table_), field_names),  // no aux_entries
            ListMatchesRequest_class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::matching::ListMatchesRequest>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // optional int64 account_id = 1;
            {::_pbi::TcParser::SingularVarintNoZag1<
                 ::uint64_t, offsetof(ListMatchesRequest, _impl_.account_id_),
                 0>(),
             {8, 0, 0,
              PROTOBUF_FIELD_OFFSET(ListMatchesRequest, _impl_.account_id_)}},
        }},
        {{65535, 65535}},
        {{
            // optional int64 account_id = 1;
            {PROTOBUF_FIELD_OFFSET(ListMatchesRequest, _impl_.account_id_),
             _Internal::kHasBitsOffset + 0, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kInt64)},
        }},
        // no aux_entries
        {{}},
    };
PROTOBUF_NOINLINE void ListMatchesRequest::Clear() {
  // @@protoc_insertion_point(message_clear_start:matching.ListMatchesRequest)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  _impl_.account_id_ = ::int64_t{0};
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ListMatchesRequest::_InternalSerialize(
    const ::google::protobuf::MessageLite& base,
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ListMatchesRequest& this_ =
      static_cast<const ListMatchesRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ListMatchesRequest::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL
        stream) const {
  const ListMatchesRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:matching.ListMatchesRequest)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional int64 account_id = 1;
  if ((cached_has_bits & 0x00000001u) != 0) {
    target = ::google::protobuf::internal::WireFormatLite::
        WriteInt64ToArrayWithField<1>(stream, this_._internal_account_id(),
                                      target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:matching.ListMatchesRequest)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ListMatchesRequest::ByteSizeLong(const MessageLite& base) {
  const ListMatchesRequest& this_ =
      static_cast<const ListMatchesRequest&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ListMatchesRequest::ByteSizeLong() const {
  const ListMatchesRequest& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:matching.ListMatchesRequest)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  {
    // optional int64 account_id = 1;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size += ::_pbi::WireFormatLite::Int64SizePlusOne(
          this_._internal_account_id());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ListMatchesRequest::MergeImpl(
    ::google::protobuf::MessageLite& to_msg,
    const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListMatchesRequest*>(&to_msg);
  auto& from = static_cast<const ListMatchesRequest&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:matching.ListMatchesRequest)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _this->_impl_.account_id_ = from._impl_.account_id_;
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ListMatchesRequest::CopyFrom(const ListMatchesRequest& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:matching.ListMatchesRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListMatchesRequest::InternalSwap(
    ListMatchesRequest* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  swap(_impl_.account_id_, other->_impl_.account_id_);
}

::google::protobuf::Metadata ListMatchesRequest::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

class ListMatchesResponse::_Internal {
 public:
  using HasBits =
      decltype(::std::declval<ListMatchesResponse>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(ListMatchesResponse, _impl_._has_bits_);
};

void ListMatchesResponse::clear_profile() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.profile_.Clear();
}
ListMatchesResponse::ListMatchesResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena,
                                  ListMatchesResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:matching.ListMatchesResponse)
}
PROTOBUF_NDEBUG_INLINE ListMatchesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    const ::matching::ListMatchesResponse& from_msg)
    : _has_bits_{from._has_bits_},
      _cached_size_{0},
      profile_{visibility, arena, from.profile_},
      page_token_(arena, from.page_token_) {}

ListMatchesResponse::ListMatchesResponse(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const ListMatchesResponse& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena,
                                  ListMatchesResponse_class_data_.base()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  ListMatchesResponse* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);

  // @@protoc_insertion_point(copy_constructor:matching.ListMatchesResponse)
}
PROTOBUF_NDEBUG_INLINE ListMatchesResponse::Impl_::Impl_(
    ::google::protobuf::internal::InternalVisibility visibility,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : _cached_size_{0}, profile_{visibility, arena}, page_token_(arena) {}

inline void ListMatchesResponse::SharedCtor(
    ::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
}
ListMatchesResponse::~ListMatchesResponse() {
  // @@protoc_insertion_point(destructor:matching.ListMatchesResponse)
  SharedDtor(*this);
}
inline void ListMatchesResponse::SharedDtor(MessageLite& self) {
  ListMatchesResponse& this_ = static_cast<ListMatchesResponse&>(self);
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.page_token_.Destroy();
  this_._impl_.~Impl_();
}

inline void* PROTOBUF_NONNULL ListMatchesResponse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) ListMatchesResponse(arena);
}
constexpr auto ListMatchesResponse::InternalNewImpl_() {
  constexpr auto arena_bits =
      ::google::protobuf::internal::EncodePlacementArenaOffsets({
          PROTOBUF_FIELD_OFFSET(ListMatchesResponse, _impl_.profile_) +
              decltype(ListMatchesResponse::_impl_.profile_)::
                  InternalGetArenaOffset(
                      ::google::protobuf::Message::internal_visibility()),
      });
  if (arena_bits.has_value()) {
    return ::google::protobuf::internal::MessageCreator::CopyInit(
        sizeof(ListMatchesResponse), alignof(ListMatchesResponse), *arena_bits);
  } else {
    return ::google::protobuf::internal::MessageCreator(
        &ListMatchesResponse::PlacementNew_, sizeof(ListMatchesResponse),
        alignof(ListMatchesResponse));
  }
}
constexpr auto ListMatchesResponse::InternalGenerateClassData_() {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &_ListMatchesResponse_default_instance_._instance,
          &_table_.header,
          nullptr,  // OnDemandRegisterArenaDtor
          nullptr,  // IsInitialized
          &ListMatchesResponse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<ListMatchesResponse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &ListMatchesResponse::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<ListMatchesResponse>(),
          &ListMatchesResponse::ByteSizeLong,
          &ListMatchesResponse::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(ListMatchesResponse, _impl_._cached_size_),
          false,
      },
      &ListMatchesResponse::kDescriptorMethods,
      &descriptor_table_matching_2eproto,
      nullptr,  // tracker
  };
}

PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::google::protobuf::
    internal::ClassDataFull ListMatchesResponse_class_data_ =
        ListMatchesResponse::InternalGenerateClassData_();

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData*
    PROTOBUF_NONNULL
    ListMatchesResponse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(
      &ListMatchesResponse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ListMatchesResponse_class_data_.tc_table);
  return ListMatchesResponse_class_data_.base();
}
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const ::_pbi::TcParseTable<
    1, 2, 1, 47, 2>
    ListMatchesResponse::_table_ = {
        {
            PROTOBUF_FIELD_OFFSET(ListMatchesResponse, _impl_._has_bits_),
            0,     // no _extensions_
            2, 8,  // max_field_number, fast_idx_mask
            offsetof(decltype(_table_), field_lookup_table),
            4294967292,  // skipmap
            offsetof(decltype(_table_), field_entries),
            2,  // num_field_entries
            1,  // num_aux_entries
            offsetof(decltype(_table_), aux_entries),
            ListMatchesResponse_class_data_.base(),
            nullptr,                            // post_loop_handler
            ::_pbi::TcParser::GenericFallback,  // fallback
#ifdef PROTOBUF_PREFETCH_PARSE_TABLE
            ::_pbi::TcParser::GetTable<
                ::matching::ListMatchesResponse>(),  // to_prefetch
#endif  // PROTOBUF_PREFETCH_PARSE_TABLE
        },
        {{
            // optional string page_token = 2;
            {::_pbi::TcParser::FastUS1,
             {18, 0, 0,
              PROTOBUF_FIELD_OFFSET(ListMatchesResponse, _impl_.page_token_)}},
            // repeated .profile.ProfileCard profile = 1;
            {::_pbi::TcParser::FastMtR1,
             {10, 63, 0,
              PROTOBUF_FIELD_OFFSET(ListMatchesResponse, _impl_.profile_)}},
        }},
        {{65535, 65535}},
        {{
            // repeated .profile.ProfileCard profile = 1;
            {PROTOBUF_FIELD_OFFSET(ListMatchesResponse, _impl_.profile_), -1, 0,
             (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
            // optional string page_token = 2;
            {PROTOBUF_FIELD_OFFSET(ListMatchesResponse, _impl_.page_token_),
             _Internal::kHasBitsOffset + 0, 0,
             (0 | ::_fl::kFcOptional | ::_fl::kUtf8String |
              ::_fl::kRepAString)},
        }},
        {{
            {::_pbi::TcParser::GetTable<::profile::ProfileCard>()},
        }},
        {{"\34\0\12\0\0\0\0\0"
          "matching.ListMatchesResponse"
          "page_token"}},
    };
PROTOBUF_NOINLINE void ListMatchesResponse::Clear() {
  // @@protoc_insertion_point(message_clear_start:matching.ListMatchesResponse)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  _impl_.profile_.Clear();
  cached_has_bits = _impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _impl_.page_token_.ClearNonDefaultToEmpty();
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL ListMatchesResponse::_InternalSerialize(
    const ::google::protobuf::MessageLite& base,
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const ListMatchesResponse& this_ =
      static_cast<const ListMatchesResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL ListMatchesResponse::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL
        stream) const {
  const ListMatchesResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(serialize_to_array_start:matching.ListMatchesResponse)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // repeated .profile.ProfileCard profile = 1;
  for (unsigned i = 0,
                n = static_cast<unsigned>(this_._internal_profile_size());
       i < n; i++) {
    const auto& repfield = this_._internal_profile().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        1, repfield, repfield.GetCachedSize(), target, stream);
  }

  cached_has_bits = this_._impl_._has_bits_[0];
  // optional string page_token = 2;
  if ((cached_has_bits & 0x00000001u) != 0) {
    const ::std::string& _s = this_._internal_page_token();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()),
        ::google::protobuf::internal::WireFormatLite::SERIALIZE,
        "matching.ListMatchesResponse.page_token");
    target = stream->WriteStringMaybeAliased(2, _s, target);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target = ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
        this_._internal_metadata_
            .unknown_fields<::google::protobuf::UnknownFieldSet>(
                ::google::protobuf::UnknownFieldSet::default_instance),
        target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:matching.ListMatchesResponse)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t ListMatchesResponse::ByteSizeLong(const MessageLite& base) {
  const ListMatchesResponse& this_ =
      static_cast<const ListMatchesResponse&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t ListMatchesResponse::ByteSizeLong() const {
  const ListMatchesResponse& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:matching.ListMatchesResponse)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  {
    // repeated .profile.ProfileCard profile = 1;
    {
      total_size += 1UL * this_._internal_profile_size();
      for (const auto& msg : this_._internal_profile()) {
        total_size +=
            ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
  }
  {
    // optional string page_token = 2;
    cached_has_bits = this_._impl_._has_bits_[0];
    if ((cached_has_bits & 0x00000001u) != 0) {
      total_size +=
          1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                  this_._internal_page_token());
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void ListMatchesResponse::MergeImpl(
    ::google::protobuf::MessageLite& to_msg,
    const ::google::protobuf::MessageLite& from_msg) {
  auto* const _this = static_cast<ListMatchesResponse*>(&to_msg);
  auto& from = static_cast<const ListMatchesResponse&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:matching.ListMatchesResponse)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  _this->_internal_mutable_profile()->MergeFrom(from._internal_profile());
  cached_has_bits = from._impl_._has_bits_[0];
  if ((cached_has_bits & 0x00000001u) != 0) {
    _this->_internal_set_page_token(from._internal_page_token());
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void ListMatchesResponse::CopyFrom(const ListMatchesResponse& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:matching.ListMatchesResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ListMatchesResponse::InternalSwap(
    ListMatchesResponse* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.profile_.InternalSwap(&other->_impl_.profile_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.page_token_,
                                       &other->_impl_.page_token_, arena);
}

::google::protobuf::Metadata ListMatchesResponse::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace matching
namespace google {
namespace protobuf {}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type _static_init2_
    [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_matching_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
