name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: whuffman36/msqrd-rpc-env:latest
    steps:
    - uses: actions/checkout@v4
    - name: Create build directory
      run: mkdir -p build
    - name: Run linters
      run: make lint
    - name: Build src, tests, static analysis
      run: make check
    - name: run tests
      run: make test
